version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - 8060:8060
    depends_on:
      - db
    environment:
      - DB_HOST=dpg-cp28gs779t8c73fotm60-a
      - DB_PORT=5432
      - DB_USER=dishes_db_user
      - DB_PASSWORD=r7Y1IaUPdozGB8o27WmOjtysdS2aoBHN
      - DB_NAME=dishes_db
    

  db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=r7Y1IaUPdozGB8o27WmOjtysdS2aoBHN
    ports:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate
    volumes:
      - ./pkg/dishes/migrations:/migrations
    command: ["-path", "/migrations", "-database",  "postgres://dishes_db_user:r7Y1IaUPdozGB8o27WmOjtysdS2aoBHN@dpg-cp28gs779t8c73fotm60-a.singapore-postgres.render.com/dishes_db", "up"]
    depends_on:
      - db

volumes:
  pgdata: