version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - 8060:8060
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=rootroot
      - DB_NAME=postgres
    

  db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=rootroot
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate
    volumes:
      - ./pkg/dishes/migrations:/migrations
    command: ["-path", "/migrations", "-database",  "postgres://postgres:rootroot@db:5432/postgres?sslmode=disable", "up"]
    depends_on:
      - db

volumes:
  pgdata: